var phrasal = [
	"I’ll dig up that plant and move it.",
	"An old Roman vase was dug up here last month.",
	"We will have to dig that tree up.",
	"They dug up a body in his garden.",
	"It’s time we dug up those potatoes.",
	"You would have to dig up the plant yourself.",
	"Dig it up once the foliage has died down.",
	"The dog keeps burying bones and digging them up.",
	"Yesterday they continued the search, digging up the backyard of a police station.",
	"They’re digging up the road outside to fix a faulty water main.",
	"They are digging up the football field to lay a new surface.",
	"They’re digging up the road just outside my flat.",
	"They tried to dig up something from his past to spoil his chances of being elected.",
	"I’ve been doing some research on our family history and I’ve dug up some interesting information.",
	"Tabloid newspapers love to dig up scandal.",
	"When we investigated his background, we dug up some interesting facts.",
	"The firm hired a private detective to dig up information on the former supervisor.",
	"She’s one of those reporters who’s always trying to dig up dirt on celebrities.",
	"Managers are too expensive and important to spend time digging up market information.",
	"His description fits perfectly the evidence dug up by Clyde."
];

var frase = [
	"Vou desenterrar aquela planta e mudá-la de lugar.",
	"Um antigo jarro romano foi encontrado enterrado aqui mês passado.",
	"Teremos que desencavar aquela árvore.",
	"Descobriram um corpo enterrado no seu jardim.",
	"Está na hora de desenterrarmos estas batatas.",
	"Você teria que desencavar a planta por conta própria.",
	"Tire-a do solo uma vez que a folhagem tenha morrido.",
	"O cachorro fica enterrando e desenterrando ossos.",
	"Ontem continuaram a busca, escavando o quintal de uma delegacia.",
	"Estão escavando a estrada ao lado fora para consertar uma rede de abastecimento de água quebrada.",
	"Estão escavando o campo de futebol para colocar uma nova superfície.",
	"Estão escavando a estrada logo ao lado do meu apartamento.",
	"Tentaram desenterrar alguma coisa do passado dele para prejudicar a sua chance de ser eleito.",
	"Estive pesquisando um pouco sobre a história da nossa família e desenterrei algumas informações interessantes.",
	"Tablóides adoram desenterrar escândalos",
	"Quando investigamos os seus antecedentes, desencavamos alguns fatos interessantes.",
	"A firma contratou um detetive particular para desenterrar informações sobre o supervisor anterior.",
	"Ela é um daqueles repórteres que está sempre tentando desenterrar sujeira sobre celebridades.",
	"Gerentes são caros e importantes demais para passar tempo desenterrando informações sobre o mercado.",
	"A sua descrição se adequa perfeitamente às provas desenterradas pelo Clyde."
];

var audio = [
	"https://mairos3.s3.sa-east-1.amazonaws.com/wp-content/uploads/2020/09/30151058/1-Ill-dig-up-that.mp3",
	"https://mairos3.s3.sa-east-1.amazonaws.com/wp-content/uploads/2020/09/30151103/2-An-old-Roman-vase.mp3",
	"https://mairos3.s3.sa-east-1.amazonaws.com/wp-content/uploads/2020/09/30151107/3-We-will-have-to.mp3",
	"https://mairos3.s3.sa-east-1.amazonaws.com/wp-content/uploads/2020/09/30151112/4-They-dug-up-a-body.mp3",
	"https://mairos3.s3.sa-east-1.amazonaws.com/wp-content/uploads/2020/09/30151118/5-Its-time-we-dug-up.mp3",
	"https://mairos3.s3.sa-east-1.amazonaws.com/wp-content/uploads/2020/09/30151123/6-You-would-have.mp3",
	"https://mairos3.s3.sa-east-1.amazonaws.com/wp-content/uploads/2020/09/30151129/7-Dig-it-up-once.mp3",
	"https://mairos3.s3.sa-east-1.amazonaws.com/wp-content/uploads/2020/09/30151140/8-The-dog-keeps.mp3",
	"https://mairos3.s3.sa-east-1.amazonaws.com/wp-content/uploads/2020/09/30151148/9-Yesterday-they.mp3",
	"https://mairos3.s3.sa-east-1.amazonaws.com/wp-content/uploads/2020/09/30151155/10-Theyre-digging-up.mp3",
	"https://mairos3.s3.sa-east-1.amazonaws.com/wp-content/uploads/2020/09/30151201/11-They-are-digging-up-the.mp3",
	"https://mairos3.s3.sa-east-1.amazonaws.com/wp-content/uploads/2020/09/30151205/12-Theyre-digging-up-the.mp3",
	"https://mairos3.s3.sa-east-1.amazonaws.com/wp-content/uploads/2020/09/30151210/13-They-tried-to-dig-up.mp3",
	"https://mairos3.s3.sa-east-1.amazonaws.com/wp-content/uploads/2020/09/30151217/14-Ive-been-doing-some.mp3",
	"https://mairos3.s3.sa-east-1.amazonaws.com/wp-content/uploads/2020/09/30151221/15-Tabloid-newspapers.mp3",
	"https://mairos3.s3.sa-east-1.amazonaws.com/wp-content/uploads/2020/09/30151227/16-When-we-investigated.mp3",
	"https://mairos3.s3.sa-east-1.amazonaws.com/wp-content/uploads/2020/09/30151232/17-The-firm-hired.mp3",
	"https://mairos3.s3.sa-east-1.amazonaws.com/wp-content/uploads/2020/09/30151236/18-Shes-one-of-those.mp3",
	"https://mairos3.s3.sa-east-1.amazonaws.com/wp-content/uploads/2020/09/30151241/19-Managers-are-too.mp3",
	"https://mairos3.s3.sa-east-1.amazonaws.com/wp-content/uploads/2020/09/30151245/20-His-description-fits.mp3"
];